apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

resources:
- ../../base

replicas:
- name: pinky-promise-backend
  count: 1
- name: pinky-promise-frontend
  count: 1

images:
- name: gcr.io/PROJECT_ID/pinky-promise-backend
  newTag: dev
- name: gcr.io/PROJECT_ID/pinky-promise-frontend
  newTag: dev

commonLabels:
  environment: development

patchesStrategicMerge:
- ingress-patch.yaml

namespace: development

