apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinky-promise-backend
  namespace: production
  labels:
    app: pinky-promise-backend
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pinky-promise-backend
  template:
    metadata:
      labels:
        app: pinky-promise-backend
        version: v1
    spec:
      serviceAccountName: production-workload-identity
      containers:
      - name: backend
        image: us-central1-docker.pkg.dev/pinky-promise-app/pinky-promise-repo/pinky-promise-backend:v1
        ports:
        - containerPort: 5001
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "5001"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-url
              key: url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-refresh-secret
              key: secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: pinky-promise-backend-service
  namespace: production
  labels:
    app: pinky-promise-backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5001
    protocol: TCP
    name: http
  selector:
    app: pinky-promise-backend

