apiVersion: v1
kind: Secret
metadata:
  name: database-url
  namespace: production
  annotations:
    secrets.cloud.google.com/secret-name: "production-database-url"
type: Opaque
data:
  url: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: production
  annotations:
    secrets.cloud.google.com/secret-name: "production-jwt-secret"
type: Opaque
data:
  secret: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-refresh-secret
  namespace: production
  annotations:
    secrets.cloud.google.com/secret-name: "production-jwt-refresh-secret"
type: Opaque
data:
  secret: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: production-workload-identity
  namespace: production
  annotations:
    iam.gke.io/gcp-service-account: production-workload-identity@pinky-promise-app.iam.gserviceaccount.com

