apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- service-accounts.yaml
- ingress.yaml

labels:
- pairs:
    app: pinky-promise
    version: v1

