apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcpsm-secret-store
  labels:
    app: pinky-promise
spec:
  provider:
    gcpsm:
      projectId: PROJECT_ID
      auth:
        workloadIdentity:
          clusterLocation: REGION
          clusterName: CLUSTER_NAME
          serviceAccountRef:
            name: pinky-promise-backend
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
  labels:
    app: pinky-promise
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-secret-store
    kind: SecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
  - secretKey: database-url
    remoteRef:
      key: ENVIRONMENT-database-url
  - secretKey: jwt-secret
    remoteRef:
      key: ENVIRONMENT-jwt-secret
  - secretKey: jwt-refresh-secret
    remoteRef:
      key: ENVIRONMENT-jwt-refresh-secret
  - secretKey: recaptcha-secret
    remoteRef:
      key: ENVIRONMENT-recaptcha-secret
  - secretKey: node-env
    remoteRef:
      key: ENVIRONMENT-node-env

