apiVersion: v1
kind: ServiceAccount
metadata:
  name: pinky-promise-backend
  labels:
    app: pinky-promise
    component: backend
  annotations:
    iam.gke.io/gcp-service-account: ENVIRONMENT-workload-identity@PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pinky-promise-frontend
  labels:
    app: pinky-promise
    component: frontend
  annotations:
    iam.gke.io/gcp-service-account: ENVIRONMENT-workload-identity@PROJECT_ID.iam.gserviceaccount.com

